apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: c8n.io/moconnorglobalizationpartnerscom/gitops-demo-app2
    newTag: v1.0.6
replicas:
  - name: gitops-demo-app2
    count: 5
patchesStrategicMerge:
  - set-pod-resources.yaml
