apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: myspotontheweb/gitops-demo-app3
  newTag: sha-75b16dc
patchesStrategicMerge:
- set-pod-resources.yaml
