apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: c8n.io/moconnorglobalizationpartnerscom/gitops-demo-app1
  newTag: sha-1c2ae7c
- name: myspotontheweb/gitops-demo-app1
  newTag: sha-b4aa7fc
patchesStrategicMerge:
- set-pod-resources.yaml
