apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: c8n.io/moconnorglobalizationpartnerscom/gitops-demo-app2
    newTag: sha-8db78d9
patchesStrategicMerge:
  - set-pod-resources.yaml
