apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: myspotontheweb/gitops-demo-app2
  newTag: sha-8b25d03
patchesStrategicMerge:
- set-pod-resources.yaml
