apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-app2
  labels:
    app.kubernetes.io/name: gitops-demo-app2
    app.kubernetes.io/instance: gitops-demo-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gitops-demo-app2
      app.kubernetes.io/instance: gitops-demo-app2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gitops-demo-app2
        app.kubernetes.io/instance: gitops-demo-app2
    spec:
      containers:
        - name: gitops-demo-app2
          image: "myspotontheweb/gitops-demo-app2:main"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
