apiVersion: v1
kind: Service
metadata:
  name: gitops-demo-app2
  labels:
    app.kubernetes.io/name: gitops-demo-app2
    app.kubernetes.io/instance: gitops-demo-app2
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: gitops-demo-app2
    app.kubernetes.io/instance: gitops-demo-app2
