apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: c8n.io/moconnorglobalizationpartnerscom/gitops-demo-app3
    newTag: v1.1.2
replicas:
  - name: gitops-demo-app3
    count: 5
patchesStrategicMerge:
  - set-pod-resources.yaml
